### ISSUE TITLE
Use hyphenatedbem for class-name-format convention

### ISSUE THREAD

**Issue by kbiedrzycki** [AirHelp/sass-lint-config-airhelp#1]
I think we may change the rule from `hyphenatedlowercase` to `hyphenatedbem`. In cockpit we try to stick to BEM naming convention and `hyphenatedlowercase` will throw warnings for classes like `block__module`. Rule `hyphenatedbem` allows same thing as `hyphenatedlowercase` + BEM naming style.

**Comment by cinkonaap** [comment]
New ruleset allows `BEM` convention, closing this one
