### ISSUE TITLE
Allow to put no-empty-rulesets

### ISSUE THREAD

**Issue by kbiedrzycki** [AirHelp/sass-lint-config-airhelp#2]
Sometimes, when you write in BEM convention and don't use nesting at all (easier to search through file) it's prefered to put empty rule, it's faster when IDE is autocomplteting code, example:

```
.block {}

.block__element {
  font-size: 12px;
}

.block__element--big {
  font-size: 20px;
}
```

**Comment by cinkonaap** [comment]
New ruleset allows `BEM` convention, closing this one
